name: FarmProtect
version: '1.0-SNAPSHOT'
main: org.ncc.farmProtect.Main
api-version: '1.20'
folia-supported: true
#commands:
#  fp:
#    permission: "fp.usage"
#permissions:
#  fp.usage:
#    default: op